server:
  port: 8081

spring:
  datasource:
    jdbc-url: jdbc:oracle:thin:@localhost:1521:xe
    username: tenancy
    password: tenancy
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update